---

- name: download java {{ java_version }}
  import_role:
    name: library
    tasks_from: download_file.yml
  vars:
    url: "{{ java_install_download_url }}"
    dest: "/tmp/{{ java_build }}"
    sha256checksum: "{{ java_checksum }}"
#    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
#    validate_certs: no

- name: check if jdk root directory exists
  stat:
    path: "{{ java_install }}"
  register: if_jdk

- name: create jdk root directory
  file:
    path: "{{ java_install }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: root
    group: root
  when:
    ((if_jdk.stat is not defined) or (if_jdk.stat.exists == false))

- name: extract archive
  unarchive:
    src: "/tmp/{{ java_build }}"
    copy: no
    dest: "{{ java_install }}"
    owner: root
    group: root

- name: create symlink
  file:
    path: "{{ java_home }}"
    src: "{{ java_version }}"
    state: link
    force: yes

- name: make Java JDK tools alternative
  alternatives:
    name: "{{ item }}"
    path: "{{ java_home }}/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items: "{{ java_jdk_tools }}"
  when: ( java_install_jdk_tools == true )
